//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JryVideo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JryVideo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 invalid input 的本地化字符串。
        /// </summary>
        internal static string EditSeries_InvalidInput_Title {
            get {
                return ResourceManager.GetString("EditSeries_InvalidInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} selector 的本地化字符串。
        /// </summary>
        internal static string FlagSelectorWindow_Title_Format {
            get {
                return ResourceManager.GetString("FlagSelectorWindow_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 audio source 的本地化字符串。
        /// </summary>
        internal static string JryEntity_AudioSource {
            get {
                return ResourceManager.GetString("JryEntity_AudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extension 的本地化字符串。
        /// </summary>
        internal static string JryEntity_Extension {
            get {
                return ResourceManager.GetString("JryEntity_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fansub 的本地化字符串。
        /// </summary>
        internal static string JryEntity_Fansubs {
            get {
                return ResourceManager.GetString("JryEntity_Fansubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 film source 的本地化字符串。
        /// </summary>
        internal static string JryEntity_FilmSource {
            get {
                return ResourceManager.GetString("JryEntity_FilmSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extension 的本地化字符串。
        /// </summary>
        internal static string JryEntity_Resolution {
            get {
                return ResourceManager.GetString("JryEntity_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 audio source 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntityAudioSource {
            get {
                return ResourceManager.GetString("JryFlagType_EntityAudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extension 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntityExtension {
            get {
                return ResourceManager.GetString("JryFlagType_EntityExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fansub 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntityFansub {
            get {
                return ResourceManager.GetString("JryFlagType_EntityFansub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 film source 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntityFilmSource {
            get {
                return ResourceManager.GetString("JryFlagType_EntityFilmSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 resolution 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntityResolution {
            get {
                return ResourceManager.GetString("JryFlagType_EntityResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 subtitle language 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntitySubTitleLanguage {
            get {
                return ResourceManager.GetString("JryFlagType_EntitySubTitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 track language 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_EntityTrackLanguage {
            get {
                return ResourceManager.GetString("JryFlagType_EntityTrackLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_VideoType {
            get {
                return ResourceManager.GetString("JryFlagType_VideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 year 的本地化字符串。
        /// </summary>
        internal static string JryFlagType_VideoYear {
            get {
                return ResourceManager.GetString("JryFlagType_VideoYear", resourceCulture);
            }
        }
    }
}
